# 파일 경로명
name: release

# 언제 실행될 것인지
on:
  push

#  push:
#    branches: [ main ]

# 실행할 job
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Starting Release"

        name: checkout
      - uses: actions/checkout@v4

      - name: permissions
        run: chmod +x gradlew

      - name: Build Documentation
        run: ./gradlew dokkaHtml

      - name: Deploy Documentation to GitHub Pages
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: github-pages
            FOLDER: compose/build/dokka/html
            TARGET_FOLDER: docs/0.x/